# Generated by Django 3.2.7 on 2021-10-19 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='up_file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='파일 업로드'),
        ),
        migrations.AddField(
            model_name='post',
            name='up_img',
            field=models.ImageField(null=True, upload_to='images/%Y_%m_%d', verbose_name='이미지 업로드'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.category', verbose_name='카테고리'),
        ),
    ]
